global_region: '1'
coastal_area: '4'
subregion: '99'
shoreline_section: '014'
gpu_id: '-1'
update: false
reset: false
planet_bool: false
function: seg
dem: ''
slope: ''
smooth_slopes: false
reference_elevation: '0'
resample_frequency: 365D
model: global
estimate: ensemble
custom_sections: ''
waterline_filter: true
year_min: '1984'
year_max: '2026'
ee_project: ee-merbok
home: /mnt/hdd_6tb/Alaska_Analysis_Images
coastseg_roi_folder: /mnt/f/Merbok/sorted_alaska
planet_folder: /mnt/c/Merbok/MerbokPlanet
